import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import JsonLd from "@/components/seo/json-ld";
import "./globals.css";

// ---------------------------------------------------------------------------
// Fonts
// ---------------------------------------------------------------------------
const poppins = localFont({
  src: [
    {
      path: "../public/fonts/Poppins-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
  display: "swap",
});

// ---------------------------------------------------------------------------
// Site-wide constants — update these when the domain goes live
// ---------------------------------------------------------------------------
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://bkfarms.in";
const SITE_NAME = "BK & Co";
const SITE_TITLE = "BK & Co — Fresh Wholesale Produce, Salem";
const SITE_DESCRIPTION =
  "BK & Co is Salem's trusted wholesale supplier of farm-fresh Onion, Potato, Garlic, Eggs & Seasonal Fruits. Bulk orders, competitive prices, on-time delivery across Tamil Nadu.";
const SITE_KEYWORDS = [
  "wholesale vegetables Salem",
  "bulk onion supplier Salem",
  "potato wholesale Salem mandi",
  "garlic wholesale Tamil Nadu",
  "egg supplier Salem wholesale",
  "fresh fruits wholesale Salem",
  "farm produce bulk Salem",
  "BK and Co Salem",
  "BK Farms Salem",
  "wholesale grocery supplier Salem",
  "vegetable distributor Salem Tamil Nadu",
  "hotel vegetable supplier Salem",
  "catering bulk grocery Salem",
  "wholesale mandi supplier Salem",
];

// ---------------------------------------------------------------------------
// Viewport (separate export — Next.js 15+ pattern)
// ---------------------------------------------------------------------------
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FBF9F5" },
    { media: "(prefers-color-scheme: dark)", color: "#14532d" },
  ],
};

// ---------------------------------------------------------------------------
// Root Metadata
// ---------------------------------------------------------------------------
export const metadata: Metadata = {
  // ── Title ──────────────────────────────────────────────────────────────────
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_NAME}`,
  },

  // ── Description & Keywords ─────────────────────────────────────────────────
  description: SITE_DESCRIPTION,
  keywords: SITE_KEYWORDS,
  category: "Wholesale Agriculture & Produce",
  classification: "B2B Agriculture Produce Wholesale Supplier",

  // ── Authorship & Publishing ────────────────────────────────────────────────
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,

  // ── Format Detection ───────────────────────────────────────────────────────
  formatDetection: {
    telephone: true,
    date: false,
    address: true,
    email: true,
    url: true,
  },

  // ── Canonical URL ──────────────────────────────────────────────────────────
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: "/",
  },

  // ── Open Graph (Facebook / WhatsApp / LinkedIn / Slack previews) ───────────
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    locale: "en_IN",
    images: [
      {
        url: "/og-image.png", // → app/og-image.png (generated by opengraph-image.tsx)
        width: 1200,
        height: 630,
        alt: "BK & Co — Fresh Wholesale Produce, Salem",
      },
    ],
  },

  // ── Twitter / X Card ──────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: ["/og-image.png"],
  },

  // ── Icons & Favicon ────────────────────────────────────────────────────────
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },

  // ── Robots ─────────────────────────────────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },

  // ── Search Engine Verification (set via environment variables) ─────────────
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    yandex: process.env.NEXT_PUBLIC_YANDEX_VERIFICATION,
    other: {
      "msvalidate.01": process.env.NEXT_PUBLIC_BING_VERIFICATION ?? "",
    },
  },

  // ── App / PWA manifest link ────────────────────────────────────────────────
  manifest: "/manifest.json",

  // ── Additional Meta & Geo Tags for Local SEO ───────────────────────────────
  other: {
    // WhatsApp / Telegram rich preview
    "og:phone_number": "+91 84899 34449",
    "og:locality": "Salem",
    "og:region": "Tamil Nadu",
    "og:country-name": "India",
    // Local Geo tags for regional ranking
    "geo.region": "IN-TN",
    "geo.placename": "Salem, Tamil Nadu, India",
    "geo.position": "11.6643;78.1460",
    ICBM: "11.6643, 78.1460",
  },
};

// ---------------------------------------------------------------------------
// Root Layout
// ---------------------------------------------------------------------------
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} font-sans antialiased`}>
      <body className="min-h-screen flex flex-col bg-[#FBF9F5] text-slate-900 selection:bg-emerald-200 selection:text-emerald-900 font-sans">
        <JsonLd />
        {children}
      </body>
    </html>
  );
}


